#development:
#  mockbot_home: 'http://mockbot.softwearcrm.com.dev'
#  api_endpoint: 'http://mockbot.softwearcrm.com.dev/api'
#  user_email: 'ricky@annarbortees.com'
#  user_token: '1u88xt29AVTQG1U5mLTP'
